name: CI

env:
  # Run on Node 14
  # versions. Note: when changing this, also change
  # jobs.node_tests.strategy.matrix.node_version and the Node version for Dart
  # dev tests.
  DEFAULT_NODE_VERSION: 14

on:
  push:
    branches: [main, feature.*]
    tags: ['**']
  pull_request:

jobs:
	build_npm:
    name: Build npm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - uses: actions/setup-node@v2
        with: {node-version: "${{ env.DEFAULT_NODE_VERSION }}"}
      - name: Deploy
        run: dart pub run grinder pkg-npm-release

  deploy_npm:
    name: Deploy npm
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - uses: actions/setup-node@v2
        with: {node-version: "${{ env.DEFAULT_NODE_VERSION }}"}
      - name: Deploy
        run: dart pub run grinder pkg-npm-deploy
        env:
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
