name: CI

env:
  # Run on Node 14
  # versions. Note: when changing this, also change
  # jobs.node_tests.strategy.matrix.node_version and the Node version for Dart
  # dev tests.
  DEFAULT_NODE_VERSION: 14

on:
  push:
    branches: [main, feature.*]
    tags: ['**']
  pull_request:

jobs:
  dart_tests:
    name: "Dart tests | Dart ${{ matrix.dart_channel }} | ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dart_channel: [stable]
        include: [{os: ubuntu-latest, dart_channel: dev}]

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with: {sdk: "${{ matrix.dart_channel }}"}
      - run: dart pub get
      - run: dart pub run grinder pkg-standalone-dev
      - name: Run tests
        run: dart pub run test -p vm -x node -r expanded

  # Unit tests that use Node.js, defined in test/.
  #
  # The versions should be kept up-to-date with the latest LTS Node releases.
  # They next need to be rotated April 2021. See
  # https://github.com/nodejs/Release.
  node_tests:
    name: "Node tests | Dart ${{ matrix.dart_channel }} | Node ${{ matrix.node_version }} | ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest]
        dart_channel: [stable]
        node_version: [14]
        include:
          # Include LTS versions on Ubuntu
          - os: ubuntu-latest
            dart_channel: stable
            node_version: 12
          - os: ubuntu-latest
            dart_channel: stable
            node_version: 10
          - os: ubuntu-latest
            dart_channel: dev
            node_version: 14

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with: {sdk: "${{ matrix.dart_channel }}"}
      - run: dart pub get
      - uses: actions/setup-node@v2
        with: {node-version: "${{ matrix.node_version }}"}
      - run: npm install
      - run: dart pub run grinder before-test
      - name: Run tests
        run: dart pub run test -j 2 -t node -r expanded

  deploy_npm:
    name: Deploy npm
    runs-on: ubuntu-latest
    needs: [sanity_checks]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - uses: actions/setup-node@v2
        with: {node-version: "${{ env.DEFAULT_NODE_VERSION }}"}
      - name: Deploy
        run: dart pub run grinder pkg-npm-deploy
        env:
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
